# Generated by Django 5.2.10 on 2026-01-30 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_practicesession_user_alter_userchecklist_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="choice",
            name="label",
            field=models.CharField(max_length=1),
        ),
        migrations.AddConstraint(
            model_name="choice",
            constraint=models.UniqueConstraint(
                fields=("question", "label"), name="uniq_choice_label_per_question"
            ),
        ),
        migrations.AddConstraint(
            model_name="choice",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_correct", True)),
                fields=("question",),
                name="uniq_correct_choice_per_question",
            ),
        ),
        migrations.AddConstraint(
            model_name="choice",
            constraint=models.CheckConstraint(
                condition=models.Q(("label__in", ["ア", "イ", "ウ", "エ"])),
                name="chk_choice_label_valid",
            ),
        ),
    ]
